### ISSUE TITLE
Refactor commands lookup/params

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#12]
The way we lookup for commands and handle params today is a bit messy, and not scalable. 

Mostly because we have created a contract for the command, establishing that every command needs the `memory`, a `key` and a `value`. Which was valid at some point but not anymore.

That causes several problems, among them we have some 'lost' commands here, the one who don't match the signature:

``` crystal
  params = Bojack::Params.from(request)
  bjcommand = Bojack::Command.from(params.command)

  if bjcommand
    response = bjcommand.execute(memory, params.key, params.value)
    socket.puts(response)
  elsif params.command == "ping"
    socket.puts("pong")
  elsif params.command == "close"
    socket.puts("closing...")
    socket.close
    break
  else
    socket.puts("error: '#{params.command}' is not a valid command")
  end
```

For further development I believe that handling this is important, new commands, for instance `delete *`, `time` ... will also not match the pattern, which in the future will lead to a huge effort on making this scalable.

My suggestion is to create an **open structure** to transport params from the server's 'network layer' to any given command. The command itself should declare internally its dependencies (params) and validate on runtime for missing or invalid params. This way we can manage in a more elegant way.

**Comment by marceloboeira** [comment]
I am already working on the solution, just want to check if @mauricioabreu / @cristianoliveira / @hugoabonizio have any thoughts on that?

**Comment by mauricioabreu** [comment]
I think that is a good idea. Your initial refactor above is a good starting point.

**Comment by marceloboeira** [comment]
@mauricioabreu thanks, the hardest part is to create now an open structure and validate it, still thinking about it.

**Comment by hugoabonizio** [comment]
What about an array-like structure? We could treat parameters as first, second, third... since not all commands use key/value format for their params. Maybe this way makes the code more confuse, I don't know, but it would be generic to all kinds of command arguments.

**Comment by mauricioabreu** [comment]
@hugoabonizio I think the problem with array is that it is not self documented. After you pass it ahead, you need to figure out what index 1 means (just an example). Not a big deal though...

**Comment by mauricioabreu** [comment]
> The command itself should declare internally its dependencies (params) and validate on runtime for missing or invalid params

arrays would do the job

**Comment by marceloboeira** [comment]
@mauricioabreu @mauricioabreu Actually the best way would be to create a class that could handle command and params and specifications, like a small `language`, e.g.: SQL , the problem is that this would take too long. For now I think it is easy if we have specific place holders.

`command* {key, param} {value(s)}`

The idea is to make it simple for now, pretty basic stuff. We can continue splitting the request on the space char, then we validate command, the only mandatory param of the request, then we let the commands itself validate the rest (like key, values and stuff..).

**Comment by mauricioabreu** [comment]
@marceloboeira agreed!

**Comment by cristianoliveira** [comment]
Hey guys. I think you may like to see NamedTuples for this case. I have seen that they have already implemented it in Crystal. here: https://github.com/crystal-lang/crystal/pull/2573

Then you can use something like this:

``` crystal
class MyCommand
  def execute(**kargs)
      puts kargs[:key]
      puts kargs[:val]
  end
end

# and use this elegant form:
command = MyCommand.new
command.execute key: "hello", val: "world"
```

:)

**Comment by marceloboeira** [comment]
@cristianoliveira yeap, for sure is a good option. I have to stop and analyze this 👍

**Comment by marceloboeira** [comment]
@cristianoliveira we really don't know the names of the params extracted from the request, if we create a named tuple with a contract, once again we are creating stipulations. I have changed some stuff, it is definitely the best way to do it, but gives a certain freedom the commands to handle their own params.

**Comment by cristianoliveira** [comment]
Hey @marceloboeira named tuple doesn't to need be used as my example. In fact, it can be used as a normal Hash accessed by symbol keys.

**Comment by cristianoliveira** [comment]
> `delete *`, `time`... will also not match the pattern, which in the future will lead to a huge effort on making this scalable.

Although I think this change is a little [YAGIN](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) we can do something as like Redis does... They have some "command table" where each command says how many params it needs and each command extracts his params from an `args` array. It makes the code really complex. 
https://github.com/antirez/redis/blob/a81a92ca2ceba364f4bb51efde9284d939e7ff47/src/server.c#L125

Otherwise, I propose instead of parse the request string into an Array in the beginning, pass it as is and leave each Command to extract its params as they need. To turns it more flexible, we could create generic extractors and each command can instantiate the extractors that fit better for its purpose. Example:

``` crystal
class KeyValueExtractor
  def extract(params) : NamedTuple
     ... lógic that returns { :key => 'bar', :value => 'foo' } 
  end
end
```

**Comment by marceloboeira** [comment]
I have committed a not so good `solution`, at least for the first release.

Gonna close this one for now! But we should really get back to it.
