### ISSUE TITLE
Installer/Packages

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#13]
This is a relevant thing we need for the first release.
- [x] Raw install 
- [x] Brew package
- [ ] Linux/Ubuntu?

**Comment by mauricioabreu** [comment]
I use Ubuntu at home. I can help to create a new package for this.
(never did this for apt, only yum)

**Comment by marceloboeira** [comment]
@mauricioabreu nice! thanks! (you could create for yum also, if it is not too much of a problem)

**Comment by mauricioabreu** [comment]
@marceloboeira You are welcome! I can do that :)

**Comment by marceloboeira** [comment]
@mauricioabreu any progress on this ? (Tonight I'll finish the brew package, the only missing thing for the release is that)

**Comment by mauricioabreu** [comment]
@marceloboeira I am sorry for it. I will try to do it today.
ps: I am sick, recovering from health problems (otitis, perforated eardrum and a severe flu).

**Comment by marceloboeira** [comment]
@mauricioabreu don't worry, just following up!

**Comment by marceloboeira** [comment]
@mauricioabreu it seems I need to release a version before making the installed for home-brew, so gonna take this out of the milestone, release the v0.1.0 and then create the installer.

**Comment by mauricioabreu** [comment]
Go ahead! I think it is true for APT packages too. Still reading about APT packaging.

**Comment by mauricioabreu** [comment]
I am trying to create a `deb` distribution but god I suck at packaging, really.
Does anyone have some experience with Debian packaging here?

**Comment by marceloboeira** [comment]
@mauricioabreu I don't :/

**Comment by hugoabonizio** [comment]
@marceloboeira @mauricioabreu maybe this can help https://github.com/jordansissel/fpm

**Comment by mauricioabreu** [comment]
@hugoabonizio woah! Let me take a look. Thank you!

**Comment by mauricioabreu** [comment]
I have a .deb file working. Tested on a new environment and it is good.

Now the problem is to understand how I push this Debian package to [Launchpad](https://launchpad.net/)
