### ISSUE TITLE
refactor: Command factory algorithm O(1) instead of O(n)

### ISSUE THREAD

**Issue by cristianoliveira** [marceloboeira/bojack#15]
Hey @marceloboeira

I understood what you tried to reach on 555a0e49435feacd16b6ffd228d36b95cedc9d96 commit. You wanted to left the command to identify itself, hold his keyword avoiding the long `switch` condition. I think it makes the things a little magic and you may forget to add it when you are creating a new command. (it has already happened :P a8d34037f479f73d7476706f769cdc13f94ff951)

The common implementation of a Factory Pattern generally uses a Map to hold all the instances. I think it makes the algorithm cleaner and better cause cost O(1) instead of the O(n). Also, it makes the factory hold the whole logic. Thus if you need to know which keyword calls a specific command is easier to find in one place.

So I propose the follow implementation:

``` crystal
COMMANDS = {
  "get" => Bojack::Commands::Get,
  "set" => Bojack::Commands::Set,
  "delete" => Bojack::Commands::Delete,
  "size" => Bojack::Commands::Size
}

def self.from(keyword) : Bojack::Commands::Command?
   COMMANDS[keyword].new if COMMANDS.exists?(keyword)
   nil
end
```

What do you think @mauricioabreu, @hugoabonizio ?

**Comment by mauricioabreu** [comment]
@cristianoliveira I think it is nice.
Your words 

> Thus if you need to know which keyword calls a specific command is easier to find in one place

convinced me.

I don't like magic things and I feel more comfortable when code is easy to find.

**Comment by hugoabonizio** [comment]
@cristianoliveira  I think it's nice too! But your example didn't compile here when I tested, so I think you wanted to say something like that:

``` crystal
COMMANDS = {
  "get"    => BoJack::Commands::Get,
  "set"    => BoJack::Commands::Set,
  "delete" => BoJack::Commands::Delete,
  "size"   => BoJack::Commands::Size,
}

def self.from(keyword) : BoJack::Commands::Command?
  return COMMANDS[keyword].new if COMMANDS.has_key?(keyword)
  nil
end
```

Maybe we should think about call a class method `execute` instead of create a new instance of the command every time. On [performance section](https://crystal-lang.org/docs/guides/performance.html) is suggested to avoid memory allocations on the heap. I think it is the case.

**Comment by cristianoliveira** [comment]
Great! Sorry, I have used an example code 😛  😆  😆

**Comment by marceloboeira** [comment]
Object oriented wise the code is a bit messy, for the same reason as before, my goal was to give the commands a responsibility of knowing about their own keywords. 

Yet, if we thing about performance makes sense, of course. However one thing has nothing to do with another. There isn't much "magic", just a class variable that represents its unchangeable keyword, it could actually be a constant. 

I would like to purpose a macro to generate the 'COMMANDS', That way we can have the best of both words (performance and object oriented design). 

We maintain the commands knowing about their keywords (cause we will need that in the future) BUT we also improve the performance by generating the commands list on build time allowing us to use a O(1) solution, which was quite well suggested.

What do you guys think about that?

**Comment by cristianoliveira** [comment]
About your point, both implementations are valid in an Object Oriented point of view. If you think about the responsibility of the Command Factory that is '_deciding which implementation execute for the given keyword_', makes sense it holding this state (keywords map). Also, if you think about the keyword property of the Commands, it only exists because of the Factory, it will not be used in another place, so it may belong to the Factory.

About the macros, I am not sure about it cause the current implementation is really simple and solve the problem pretty well. Introducing macros just for it I think may be overkill.

**Comment by marceloboeira** [comment]
@cristianoliveira I agree that for now there is nowhere else using the keywords, however I am quite sure there will be at some point, to avoid any further discussion we can leave that for the time being.

Let's follow @cristianoliveira's suggestion, we need this ready so we can finish #12 👯 

Can you open a pull-request with this @cristianoliveira ?

**Comment by cristianoliveira** [comment]
Sure! Or even better, I think that @hugoabonizio has already implemented so would be fair leave him to do the PR. Could do you Hugo?

**Comment by hugoabonizio** [comment]
OK! I pushed the code I adapted from the @cristianoliveira suggestion, the PR is here #16 :+1:
