### ISSUE TITLE
Strange behavior when reusing connection

### ISSUE THREAD

**Issue by hugoabonizio** [marceloboeira/bojack#17]
I'm getting a strange result when benchmarking BoJack Client, the performance when I reuse the same TCPSocket is much worse than opening a new one for each command. The code is [here](https://gist.github.com/hugoabonizio/79cb90645a50dbf6b4d8dd7aed920c84).

```
             user     system      total        real
shared   0.000000   0.030000   0.030000 (  7.918069)
new      0.000000   0.010000   0.010000 (  0.010263)
```

I noticed that @marceloboeira is making some tests on branch `benchmarks`, are you having the same problem?

**Comment by mauricioabreu** [comment]
Have you tried to disable Nagle algorithm by setting tcp_nodelay to true?
https://crystal-lang.org/api/0.18.7/TCPSocket.html#tcp_nodelay%3F-instance-method

**Comment by mauricioabreu** [comment]
Other programming languages have this very same problem due to how Nagle works.  If it works, we should think about it. Here is a nice reading about the topic: https://www.extrahop.com/community/blog/2009/to-nagle-or-not-to-nagle-that-is-the-question/

**Comment by mauricioabreu** [comment]
My results:

```
➜  bojack git:(master) ✗ crystal run --release benchmarks/socket_nagle.cr 
             user     system      total        real
shared   0.000000   0.000000   0.000000 (  0.007952)
new      0.000000   0.010000   0.010000 (  0.015957)
```

**Comment by marceloboeira** [comment]
@mauricioabreu / @hugoabonizio I was doing the same thing last night, but I was trying to measure how long it would take to have like 100_000 or 1_000_000 keys in the database. The thing is we have some consistency/concurrency issues on handling several requests. 

I had to test this with ruby, because I wasn't able to create many parallel tcp requests with Crystal for some reason. 

Take a look at the `benchmarks` branch.

**Comment by hugoabonizio** [comment]
Interesting! I didn't know about Nagle's algorithm yet. Disabling for both client and server the performance was much better. It seems like Redis disables [this by default](https://github.com/antirez/redis/issues/921), should we do the same?

**Comment by mauricioabreu** [comment]
@hugoabonizio I don't know. I suck at TCP but it is worth a try. :)

@marceloboeira what is this "consistency/concurrency" problem exactly?

**Comment by marceloboeira** [comment]
@hugoabonizio gonna have a look on this, but if it increases performance and redis is doing it, probably we should!

**Comment by marceloboeira** [comment]
@mauricioabreu it seems that we are not correctly implementing the "secure" routine for the TCP connection/request handler. 

Please read #19 for a complete answer!

**Comment by marceloboeira** [comment]
@hugoabonizio will you handle the Nagle's thing? cause I would like to try solving the concurrency problems yet it will take me a while.

**Comment by hugoabonizio** [comment]
@marceloboeira OK!
