### ISSUE TITLE
Use waffle.io to manage issues/tasks/roadmap/releases

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#18]
I am 100% for using waffle, but would like your suggestion/input on that.

Please: @cristianoliveira / @mauricioabreu / @hugoabonizio / @joaocv3 

If you are not familiar with, please: http://waffle.io

**Comment by mauricioabreu** [comment]
I am ok with this! 👍

**Comment by hugoabonizio** [comment]
I never used waffle.io before, but let's try! My account is _hugoabonizio_ too.

**Comment by marceloboeira** [comment]
@hugoabonizio is the same GitHub account, waffle uses the GitHub issues, it just shows everything as a Kanban board, which makes it easy to manage and organize. (priority, backlog, roadmap, todo/doing/done).

**Comment by mauricioabreu** [comment]
It is a pretty cool tool! Thanks for bringing it. It will help a lot.

**Comment by marceloboeira** [comment]
@mauricioabreu thanks, I was using a long time ago for solo projects, but now it is even better with you guys helping me out 👍

**Comment by mauricioabreu** [comment]
haha, I am just trying to learn something new here. "Helping" does not fit right now lol

**Comment by marceloboeira** [comment]
@mauricioabreu when we are learning we are usually not afraid to make mistakes, that is usually when we don't limit ourselves to any suggestion/possibility and that is when the best ideas emerge.

**Comment by mauricioabreu** [comment]
@marceloboeira  You are goddam right.

**Comment by joaocv3** [comment]
@marceloboeira  sounds good. Just signed up.
