### ISSUE TITLE
ASCII logo on boot

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#20]
It would be seek to have a BoJack Horse ASCII logo when booting the server.

See:
http://www.asciiworld.com/-Horses-.html

Please show us the logo here before creating the code so we can decide.

Also remember to put the name and version of the project. (BoJack v0.0.0 for now).

**Comment by hugoabonizio** [comment]
I'm not good with ASCII art, but I'm leaving here this official [Todd in ASCII](http://bojackhorseman.com/topsecret.js).

**Comment by mauricioabreu** [comment]
Should the logo be one of these in the URL you added?

**Comment by marceloboeira** [comment]
@mauricioabreu I think a simple ASCII horse should be enough, any, not necessarily from my link.

**Comment by mauricioabreu** [comment]
```
        _|\ _/|_,
      ,((\\``-\\\\_
    ,(())      `))\
  ,(()))       ,_ \
 ((())'   |        \
 )))))     >.__     \
 ((('     /    `-. .c|
         /        `-`'
```

**Comment by mauricioabreu** [comment]
This one is very cool! :)

**Comment by marceloboeira** [comment]
@mauricioabreu yeap, it is my favorite haha 🐴
