### ISSUE TITLE
[Logger] Define output

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#23]
Currently the logger is hardcode to the STDOUT, which may be not a very good option for every user, what about defining this in the CLI?

e.g.: `bojack server --log ./shared/logs/bojack.log` 

BoJack would have to create a new file, with the given prefix and add a timestamp:

e.g.:  `./shared/logs/bojack_201609201010.log`

**Comment by hugoabonizio** [comment]
@marceloboeira what `201609201010` is suposed to be? 2016-09-20 10:10?

**Comment by marceloboeira** [comment]
@hugoabonizio ahaha something like it, doesn't have to be a different file for each, but I would recommend that instead of opening old files and writing over it...

**Comment by hugoabonizio** [comment]
@marceloboeira OK! I add seconds to the timestamp too. Check #35 if it is the expected behavior.

**Comment by marceloboeira** [comment]
@hugoabonizio seems OK, we just have to create at somepoint an abstraction to logger so we can implement and test this kind of stuff, otherwise `cli.cr` is going to be huge and buggy.

**Comment by hugoabonizio** [comment]
@marceloboeira you're right!
