### ISSUE TITLE
[CLI] Hostname / Help conflict flag

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#27]
Both help and hostname flags have the same "short" version to -h. 

Usually the priority is for the help command. 

We can either change the param name, or the short name for the flag.

**Comment by mauricioabreu** [comment]
I think we can just remove the short option and let it be just `--hostname`.

**Comment by hugoabonizio** [comment]
Redis seems to handle this by using -h as a boolean flag, if it is present and doesn't have a value, it is the short version of "help". I don't know how to do something like this using the `mrrooijen/commander` shard. We can check if it is keeping the default value and then assign this to help command.

**Comment by marceloboeira** [comment]
@hugoabonizio so help could change to `--help` only.
