### ISSUE TITLE
BoJack client shard

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#36]
We need a special repository for the BoJack client shard, so that Crystal developers can install only the client, as we already have the Python client.  

Client only, the console should remain under this repository.

@hugoabonizio If you want to be in charge of this you could create the `bojack.cr` repository that would be a client for BoJack, move the content from this repository to yours and also use the shard here to point to the `Client` class.

If you do so, I would like to ask to also rename the CLI command, from `client` to `console` to avoid any future misunderstandings.

I would like to as both @mauricioabreu and @hugoabonizio that the clients follow the release number of the server, so it is easy to identify compatible versions.

**Comment by mauricioabreu** [comment]
Hm, about the last parte (versioning): I don't know if it will work for Python.

Python does take in consideration the version number to upload a package to PyPI (Python Package Index). If a bug is fixed on the client package, it could not be updated.

**Comment by hugoabonizio** [comment]
@marceloboeira OK, I'm doing this!

@mauricioabreu you can update the PATCH version of the package, I think. So your package for BoJack v0.2.0 can be 0.2.0.1, for example.

**Comment by marceloboeira** [comment]
@hugoabonizio perfect!

I was not clear about the patch version. @mauricioabreu Thanks for remind us.

**Comment by mauricioabreu** [comment]
@marceloboeira yey, you are welcome :)

**Comment by hugoabonizio** [comment]
I created the repository https://github.com/hugoabonizio/bojack.cr and named the shard "bojack-client" to avoid conflicts.

To write the specs I'm suposing the user has BoJack already running at 127.0.0.1:5000, but to test on Travis I think I should include this repo as a development_depencency.

**Comment by marceloboeira** [comment]
@hugoabonizio take a look how the http://github.com/marceloboeira/bojack-kemal-heroku is doing this, I use bojack (this repo) as a shard and run the server in the same process. This way you "inject" bojack in the same process as a dependency.

Just remember to make it a development_dependency, in order to prevent circular references.

**Comment by marceloboeira** [comment]
As soon as you finish and release a stable version, we remove the code from here and close this issue.

**Comment by hugoabonizio** [comment]
Closed in #38.
