### ISSUE TITLE
Add TTL to keys

### ISSUE THREAD

**Issue by hugoabonizio** [marceloboeira/bojack#40]
I think we should implement a Time To Live to keys. Adding a timeout to a key is an important feature to use BoJack as a caching backend, for example.

**Comment by marceloboeira** [comment]
@hugoabonizio interesting, the only thing we would have to create a side-loop to collect the expired keys.

**Comment by hugoabonizio** [comment]
Working on this I was wondering about safety of this side-loop (a kind of garbage collector) and that a lock is needed for some cases, see #41.
