### ISSUE TITLE
Request timeouts

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#52]
## Feature

Use a global request timeouts setup

That would prevent any connection lock because of a `Request` is stuck.

## Implementation  

Currently:
```
Main Loop
  -> Message
     -> Channel(Request)

Channel Loop
   -> Request
     -> Command
        -> Response
```

After:
```
Main Loop
  -> Message
     -> Channel(Request)

Channel Loop
   -> Timeout Handler
     -> Request
       -> Command
         -> Response
```

Then the loop on the channel waits for the `Request` to finish or raise an exception if runs out of time.

## Changes

Initially, the timeout setup will be defined only on server startup and will be shared among all connections:
`bojack server [params] --timeout <value>` 

At some point it might be interesting to have a specific timeout per client, making it more flexible.
`bojack console --timeout <value>`

Or, as a command:
`timeout <value>`

@hugoabonizio @mauricioabreu @joaocv3 any thouths?

**Comment by hugoabonizio** [comment]
I was searching for timeout patterns in Crystal (crystal-lang/crystal#2990) and since rescuing exceptions seems to be slow I think we can handle timeouts with something like:

``` crystal
ch = Channel(Int32?).new

spawn do
  sleep 1
  ch.send nil # TIMEOUT
  ch.close
end

spawn do
  sleep 2
  ch.send 1 # TOO LATE
end

res = ch.receive
puts "timeout" if res.nil?
```

**Comment by marceloboeira** [comment]
@hugoabonizio interesting, I was not aware, good catch!

I am refactoring the exception handling, #50. However, the #50 case it is not flow related, but exception handling for real. If something bad happens we need to manage to not affect other connections, but for this case (timeout) might be interesting to take a look at this pattern.

I am not sure how can we control the channel being opened and closed for each timeout though.

**Comment by hugoabonizio** [comment]
Maybe we don't need to close the channel. Take a look at my attempt to implement [this](https://gobyexample.com/timeouts) pattern: https://github.com/hugoabonizio/timeout.cr

**Comment by marceloboeira** [comment]
@hugoabonizio Really cool! Simple syntax  and it seems to solve the problem. Can we compare the performance against exceptions?
