### ISSUE TITLE
[Build Error] console.cr

### ISSUE THREAD

**Issue by ghost** [marceloboeira/bojack#53]
I'm having trouble compiling bojack for my system:
`Linux lawliet 4.8.0-51-generic #54~16.04.1-Ubuntu SMP Wed Apr 26 16:00:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

```
Error in src/bojack/bootstrap.cr:3: instantiating 'BoJack::CLI:Class#run(Array(String))'

BoJack::CLI.run(ARGV)
            ^~~

in src/bojack/cli.cr:10: instantiating 'Commander::Command:Class#new()'

      cli = Commander::Command.new do |command|
                               ^~~

in src/bojack/cli.cr:10: instantiating 'Commander::Command:Class#new()'

      cli = Commander::Command.new do |command|
                               ^~~

in src/bojack/cli.cr:71: instantiating 'Commander::Commands#add()'

        command.commands.add do |command|
                         ^~~

in src/bojack/cli.cr:71: instantiating 'Commander::Commands#add()'

        command.commands.add do |command|
                         ^~~

in src/bojack/cli.cr:91: instantiating 'BoJack::Console:Class#new(String, (Int32 | Int64))'

            BoJack::Console.new(options.string["hostname"], options.int["port"]).start
                            ^~~

instance variable '@client' of BoJack::Console must be BoJack::Client, not Nil

Error: instance variable '@client' is initialized inside a begin-rescue, so it can potentially be left uninitialized if an exception is raised and rescued
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 1
```
The compiler alerts about a problem with:
@client = BoJack::Client.new(@hostname, @port) _## src/bojack/console.cr ##_

Since it was initialized inside a begin, the compiler understands that it can eventually be used without being initialized, it pretty much ignores having an exit -1 in the rescue.

Only to solve the problem and move on, I changed the line @client = BoJack::Client.new(@hostname, @port)  to BoJack::Client.new(@hostname, @port) in order to first test the connection and after the rescue, assuming that at that point the request was successful, I created the variable with the same parameters used in the test: @client = BoJack::Client.new(@hostname, @port)

For example:
```
  def initialize(@hostname : String = "127.0.0.1", @port : Int8 | Int16 | Int32 | Int64 = 5000)
      begin
        BoJack::Client.new(@hostname, @port)
      rescue exception
        puts exception.message
        exit -1
      end

      @client = BoJack::Client.new(@hostname, @port)
    end
```

This solved my problem despite knowing that it isn't the best solution. 
So, anyway, I hope this helps in some way.

**Comment by ghost** [comment]
As promised, @marceloboeira

**Comment by marceloboeira** [comment]
@voidyo which version of crystal are you using?

**Comment by ghost** [comment]
I'm using the [Ubuntu ppa repository version](https://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html):
`Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0`

I installed LLVM 3.9 and the [libraries listed in Crystal's github](https://github.com/crystal-lang/crystal/wiki/All-required-libraries)

**Comment by marceloboeira** [comment]
We support only `0.20` for now. I was trying to update it, but I don't have time now :/

**Comment by ghost** [comment]
Don't worry, for now this was the only problem I encountered with `0.22`. Anyway, I'll test bojack with this modification with this version of Crystal, I'll give you feedback on any issues.

**Comment by marceloboeira** [comment]
@voidyo can you check now?

**Comment by ghost** [comment]
@marceloboeira Yeah, it's working now, thanks guys :smiley:

**Comment by marceloboeira** [comment]
thanks @hugoabonizio 👍
