### ISSUE TITLE
RESP support

### ISSUE THREAD

**Issue by hugoabonizio** [marceloboeira/bojack#55]
Hi!

Following the idea in #39, I was playing with [RESP](https://redis.io/topics/protocol) protocol parsing and I think that it would be pretty easy to add a Redis compatible mode to BoJack!

We can start the server with a ```bojack server --resp``` flag to start a server that understands Redis protocol. I've made some work here: https://github.com/hugoabonizio/resp.cr

WDYT @marceloboeira?

**Comment by marceloboeira** [comment]
I think it is a nice idea 👍

**Comment by hugoabonizio** [comment]
I opened PR #56 to work on it!
