### ISSUE TITLE
Inconsistent error message for pop command

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#7]
```
set a 1
1
append a 2
["1", "2"]
pop a
2
pop a
1
pop a
error: 'a' is not a valid key
get a
[]
```

When `a` has no elements, returns that `a` is an invalid key. However if you use the `get` command with the same key the return is an empty array, proving that the key IS valid, but empty.

The error message should be different when is a list is empty.

**Comment by mauricioabreu** [comment]
```
`a` has no elements to pop
```

?

**Comment by marceloboeira** [comment]
@mauricioabreu yes, or even no error message at all, I mean, is it necessary to raise an error for that? 

@cristianoliveira what you think?

**Comment by mauricioabreu** [comment]
@marceloboeira what happens if you pop from a regular empty list?

**Comment by cristianoliveira** [comment]
I think it is not really an error in itself, but just that there is nothing to pop. For example, in ruby when you pop the entire list the last value is nil. Maybe return nothing?

**Comment by cristianoliveira** [comment]
We should raise an error when there is no list for the given key.

**Comment by marceloboeira** [comment]
@cristianoliveira yeap, that is my point, it is not an error but an attempt to remove an item. So just returning nothing would be a better option. To handle an empty value is the user job 👍

**Comment by marceloboeira** [comment]
@cristianoliveira yes we should, currently that works, but the way it was implemented result on this issue as a side effect.

**Comment by mauricioabreu** [comment]
@marceloboeira @cristianoliveira I came from Python where pop from an empty list raises an exception, sorry ;~

**Comment by cristianoliveira** [comment]
@marceloboeira To implement that we need to change `Bojack::Memory` adding `pop` method. Then instead of using the delete method to get the value implement a pop directly on the array.

@mauricioabreu I know how you feel  :(
Python does it because of looking at the implementation it permits you to pass an optional param for pop `list.pop(0)` and it will start popping from the index passed. So they need to ensure that it will behave like an access list by index. While in Ruby you can pass a param to pop but it says how many items you want to pop.

For this specific case, I think it may not is the correct approach cause the Bojack client will need to deal with errors. The redis-server approach is the same([see here](https://github.com/antirez/redis/blob/ab73544396de1ba9ca7ef6b065517c9411a1a1bf/src/quicklist.c#L1323)) then each client implements following the language conventions.

**Comment by cristianoliveira** [comment]
I just notice that Crystal behaves like as Python. :/

**Comment by cristianoliveira** [comment]
I just noticed that Crystal behaves like as Python.
So to fix it just catch the `IndexError` and returns nil

**Comment by mauricioabreu** [comment]
@cristianoliveira good "catch" lol

**Comment by mauricioabreu** [comment]
@cristianoliveira yes, Python has this behavior. Python likes to follow a philosophy to raise errors instead of None/False or any "falsey" values.

Your solution seems elegant.

**Comment by marceloboeira** [comment]
You guys rock 🤘🏻
Thanks!

**Comment by mauricioabreu** [comment]
@cristianoliveira I tried to just catch `IndexError` but after removing all elements from the cache, it returns a `invalid key error` from the `read` function.

**Comment by mauricioabreu** [comment]
Do you believe me if I say that I tried the very same example you provided but `pop a` for an empty list did not raise an exception? :confused:

**Comment by marceloboeira** [comment]
@mauricioabreu one of the reasons for why we need functional test for this. Are you with the last version?

**Comment by cristianoliveira** [comment]
Hey @mauricioabreu thinking better catch the `IndexError` is not the best solution cause it is not explicitly enough. You need to know that `list.pop` raises it. So the best approach may be this one:

``` crystal
  class Pop < Command
      def execute(memory, key, value)
        list = memory.read(key)

        return nil if list.empty?
        list.pop
      rescue
        "error: '#{key}' is not a valid key"
      end
  end
```

What do you think guys?

**Comment by mauricioabreu** [comment]
@marceloboeira Well it looks like i was running an old version or I don't know how to reproduce it. I will try to reproduce the error a little more, but don't worry with it.

**Comment by mauricioabreu** [comment]
@cristianoliveira I was thinking of something like this but I was afraid of being a bad solution.

I created a [pull request](https://github.com/marceloboeira/bojack/pull/10) with the solution you provided

**Comment by cristianoliveira** [comment]
Great! I will take a look :)

**Comment by marceloboeira** [comment]
@mauricioabreu thanks!
