### ISSUE TITLE
Handle connection EXIT signal

### ISSUE THREAD

**Issue by marceloboeira** [marceloboeira/bojack#8]
As @cristianoliveira already mentioned, we should leave on EXIT signal and not with the close command. 

I have created this issue for us to discuss whether we should keep or not the close command and how should we handle EXIT signal from telnet connections.

Relevant information:
http://redis.io/commands/QUIT

**Comment by hugoabonizio** [comment]
I think that "close" command is important to make sure that all pending responses are over and gracefully close the connection to avoid inconsistent states in the future.

**Comment by marceloboeira** [comment]
@hugoabonizio yeap, but we should also handle the graceful exit and the EXIT signal from the telnet client. 

Further more I believe we must create our own client. One of my next experiments is to create an application using BoJack to manage a counter, or something, and check its performance.

**Comment by hugoabonizio** [comment]
I started to write a simple client to BoJack a few days ago, but I don't know where to put (maybe another repository?). As the owner, what you think?

**Comment by marceloboeira** [comment]
Hugo, 

That is very nice, since the concept of the project my ideia was a single binary file, so you can place it on this repository, same level as the "server" folder -> `src/bojack/client`. 
The entry point is the `cli.cr` file.

Usage: `bojack client <params>`

If you need/want any help let us know. Also I can add you as a contributor so you can create branchs on the main repository, which makes it easy for us to follow up on your work and doubts.

Thanks in advance!

**Comment by hugoabonizio** [comment]
It would be great! :smile:

**Comment by marceloboeira** [comment]
@hugoabonizio can you handle this? We just want to ensure that the connection closes when we hit "control-c" for instance in the client.

**Comment by hugoabonizio** [comment]
@marceloboeira Alright!

**Comment by marceloboeira** [comment]
https://github.com/sdogruyol/kemal/blob/master/src/kemal.cr#L27
